# Site settings
title: "Joan Gallego Webpage"
description: "Personal webpage of Joan Gallego."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Joan Sebastián<br/>Gallego Murillo"
resume_title:                   "Bioprocess engineer • Chemical engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jsgallegom[at]outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+57) 317 1406083"
resume_contact_address:         "Bogotá, Colombia"

resume_header_contact_info:     "Bogotá, Colombia • (+57) 317 1406083 • jsgallegom[at]outlook.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>PhD Bioprocess Engineer with 7 years of experience in scaling up cultivation systems, including the optimization of media formulations and the development of feeding strategies to reduce operating costs. I have worked with bacterial, yeast, fungal and animal cell cultures.</p> <p>My work and academic experience has been shaped by the idea of building bridges: connecting lab work to modeling and simulations, cell biology knowledge to biochemical engineering, and fundamental research to process optimization. I am passionate about bringing science fiction ideas to reality using biotechnology.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true
resume_section_publications:    true
resume_section_conferences:     true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/synthbiont"
  # resume_twitter_url:           "http://twitter.com/joangallego"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joan-gallego"
  # resume_instagram_url:         "https://instagram.com/joangallego"
  resume_website_url:           "http://joangallego.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_orcid_url:             "https://orcid.org/0000-0003-2381-2012"
  resume_spanish_url:             "https://www.joangallego.com/es.html"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
